apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: echoserver-grpc-transcoder
  namespace: test
spec:
  workloadSelector:
    labels:
      app: echoserver
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        portNumber: 50051
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.grpc_json_transcoder
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          proto_descriptor: "/etc/proto/echo.pb"
          services: 
            - "echo.Echo"
          print_options:
            add_whitespace: true
            always_print_primitive_fields: true
            always_print_enums_as_ints: false
            preserve_proto_field_names: false